### ISSUE TITLE
What does the boardSize and escapePoint mean?

### ISSUE THREAD

**Issue by armnotstrong** [jeantimex/klotski#31]
Hi,

I can't quite understand the property `boardSize` and `escapePoint`, for example, in the demonstration, the first problem "横刀立马", has a board of  5 rows and 4 columns, so why the `boardSize` is `[6,6]` instead of `[5,4]` and how come the escape point is `[2,4]` instead of `[5,1]` ? 

![klotski](https://user-images.githubusercontent.com/3839691/94441920-e9605b00-01d5-11eb-948e-c65f0e5d38d0.png)

**Comment by jeantimex** [comment]
Hi @armnotstrong , thanks for pointing out the bug! The `boardSize` should be [5, 4] meaning 5 rows and 4 columns, and the `escapePoint` should be [3, 1] meaning the row 3 and col 1, they are all 0-based index.

I fixed the custom-game.json and also wrote a simple demo with drag and drop support here: https://jsfiddle.net/jeantimex/347dt2oa/

Hope that helps. :)
